# Generated by Django 2.0.4 on 2018-04-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
