# Generated by Django 2.0.4 on 2018-04-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20180419_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(max_length=15),
        ),
    ]
