# Generated by Django 2.0.4 on 2018-04-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('subscribe', models.CharField(max_length=15)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
