# Generated by Django 2.0.4 on 2018-04-28 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='subscribe',
            new_name='level',
        ),
    ]
